import Head from "next/head";
import Image from "next/image";
import Carousel from "/components/carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NSU Mars Ex 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* carousel */}
      <div>
        <Carousel />
      </div>
    </div>
  );
}
